
# this is a comment 
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cgiardina6d3947/docker-react-cg -f Dockerfile.dev .

script:
  - docker run -e CI=true cgiardina6d3947/docker-react-cg npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-cg"
  env: "DockerReactCg-env-1" 
  bucket_name: "elasticbeanstalk-us-east-1-353663474754"
  bucket_path: "docker-react-cg"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
