
# this is a comment 
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cgiardina6d3947/docker-react-cg -f Dockerfile.dev .

script:
  - docker run -e CI=true cgiardina6d3947/docker-react-cg npm run test --coverage